/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Supabase(PostgreSQL) 연결 상태와 버전 정보를 JSON으로 반환한다.
         *
         *     - 성공 시: {"database": "연결됨", "postgres_version": "..."}
         *     - 실패 시: 502와 함께 에러 메시지 반환 (.env 접속 정보를 확인할 것)
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Profile
         * @description `public.profile` 테이블에서 이름·한 줄 소개·상세 소개·마지막 수정 시각을 조회한다.
         *
         *     - 200: {"profile": {...}}
         *     - 404: 아직 데이터가 한 줄도 없는 경우 (테이블은 있으나 seed가 안 된 상태)
         */
        get: operations["get_profile_api_profile_get"];
        /**
         * Update Profile
         * @description 로그인(관리자)한 경우에만 프로필을 수정한다. id·updated_at은 서버가 자동 관리한다.
         */
        put: operations["update_profile_api_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session
         * @description 현재 브라우저가 유효한 관리자 세션 쿠키를 가지고 있는지 확인한다.
         */
        get: operations["get_session_api_auth_session_get"];
        put?: never;
        /**
         * Login
         * @description 관리자 비밀 코드를 검증하고, 통과하면 서명된 세션 쿠키를 발급한다.
         */
        post: operations["login_api_auth_session_post"];
        /**
         * Logout
         * @description 세션 쿠키를 제거해 로그아웃 처리한다 (방문자 모드로 복귀).
         */
        delete: operations["logout_api_auth_session_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuthStatus */
        AuthStatus: {
            /** Authenticated */
            authenticated: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Passcode */
            passcode: string;
        };
        /**
         * Profile
         * @description 이력서 소유자의 기본 프로필 정보 DTO. DB 테이블 원형을 그대로 노출하지 않고
         *     외부로 나가는 필드만 명시적으로 정의한다 (내부 전용 컬럼이 추가되어도 자동 유출되지 않음).
         */
        Profile: {
            /** Id */
            id: number;
            /** Full Name */
            full_name: string;
            /** Headline */
            headline: string;
            /** Summary */
            summary: string | null;
            /** Updated At */
            updated_at: string;
        };
        /** ProfileResponse */
        ProfileResponse: {
            profile: components["schemas"]["Profile"];
        };
        /** ProfileUpdate */
        ProfileUpdate: {
            /** Full Name */
            full_name: string;
            /** Headline */
            headline: string;
            /** Summary */
            summary?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_profile_api_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
        };
    };
    update_profile_api_profile_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_auth_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_session_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatus"];
                };
            };
        };
    };
}
